name: declmig_flutter
description: Flutter client for Declarative Migrations
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_auth_flutter:
    git:
      url: https://github.com/shared-auth/shared-auth-flutter.git
      ref: ff47465d3cd1f1836f31c99b57b1785d5dbe6929

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/app-logo.png
