name: declmig_flutter
description: Flutter client for Declarative Migrations
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  ores_flutter:
    git:
      url: https://github.com/ORESoftware/ores-flutter.git
      ref: b39f9a1371ddd19289ad46fd5501d20524e5fc56
